### ISSUE TITLE
Windows instructions for getting started

### ISSUE THREAD

**Issue by slucaskim** [tkpcchurch/ichthys#20]
Windows subsystem for linux installation required for ansible: https://www.jeffgeerling.com/blog/2017/using-ansible-through-windows-10s-subsystem-linux

**Comment by hylee1201** [comment]
https://github.com/Microsoft/BashOnWindows/issues/549

**Comment by hylee1201** [comment]
If vagrant (Windows 10, cmdline) is used, refer to the following.

https://stackoverflow.com/questions/46723611/vagrant-timed-out-while-waiting-for-the-machine-to-boot-in-windows-10

**Comment by hylee1201** [comment]
https://github.com/xilun/cbwin/releases

**Comment by slucaskim** [comment]
https://github.com/tkpcchurch/ichthys/pull/22
